### ISSUE TITLE
ValueError: Object arrays cannot be loaded when allow_pickle=False

### ISSUE THREAD

**Issue by TheFunEmbargo** [macaodha/batdetect#10]
I run the code, but it crashes... ideas?

C:\Users\User\Documents\000_Work_Devs\Bat Spec\batdetect-master\batdetect-master\bat_eval>python run_detector.py
Processing         2 files
Input directory    wavs
Results directory  results

Traceback (most recent call last):
  File "run_detector.py", line 115, in <module>
    det = detector.CPUDetector(det_model_file, det_params_file)
  File "C:\Users\User\Documents\000_Work_Devs\Bat Spec\batdetect-master\batdetect-master\bat_eval\cpu_detection.py", line 36, in __init__
    self.weights = np.load(weight_file, encoding='latin1')
  File "C:\Python27\lib\site-packages\numpy\lib\npyio.py", line 447, in load
    pickle_kwargs=pickle_kwargs)
  File "C:\Python27\lib\site-packages\numpy\lib\format.py", line 696, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False

C:\Users\User\Documents\000_Work_Devs\Bat Spec\batdetect-master\batdetect-master\bat_eval>

**Comment by macaodha** [comment]
Hi,

What version of numpy are you using?

**Comment by TheFunEmbargo** [comment]
1.16.6 on py 2.7, 1.19.1 on py 3.8 - same ish with both

**Comment by macaodha** [comment]
I would suggest verifying with the package versions specified here:
https://github.com/macaodha/batdetect/tree/master/bat_eval#requirements

I've seen this problem before and I think it is likely a numpy version issue. 

Not much use to you know but I have a newer codebase in development that has improved performance and better integration with modern deep learning frameworks.

**Comment by TheFunEmbargo** [comment]
I have uninstalled and reinstalled the correct numpy version, it now throws a new error?!?!

C:\Users\User\Documents\000_Work_Devs\Bat Spec\batdetect-master\batdetect-master\bat_eval>python run_detector.py
Processing         2 files
Input directory    wavs
Results directory  results


 1 of 2          \Pipistrellus_pipistrellus.wav
  dur 0.213 (secs) , fs 250000
Traceback (most recent call last):
  File "run_detector.py", line 133, in <module>
    detection_thresh)
  File "run_detector.py", line 74, in run_model
    low_res=True)
  File "C:\Users\User\Documents\000_Work_Devs\Bat Spec\batdetect-master\batdetect-master\bat_eval\cpu_detection.py", line 84, in run_detection
    call_time, call_prob = nms.nms_1d(prob, nms_win, chunk_duration)
AttributeError: 'module' object has no attribute 'nms_1d'

C:\Users\User\Documents\000_Work_Devs\Bat Spec\batdetect-master\batdetect-master\bat_eval>

**Comment by macaodha** [comment]
Compile fast non maximum suppression by running: python setup.py build_ext --inplace. 

See the following for more info:
https://github.com/macaodha/batdetect/issues/8#issuecomment-611486114

**Comment by TheFunEmbargo** [comment]
Sorry to be rather incompetent but not even the suggested line runs without hitch, I'm mostly using correct package versions where they would install.

C:\Users\User\Documents\000_Work_Devs\Bat Spec\batdetect-master\batdetect-master\bat_eval>python setup.py build_ext --inplace
running build_ext
building 'nms' extension
error: Unable to find vcvarsall.bat

**Comment by macaodha** [comment]
I'm guessing you are running it on Windows? If so it can be a bit trickoer to setup. 

I would suggest changing the following lines 
https://github.com/macaodha/batdetect/blob/343c0acce23b7ea38ac6014d1551d24ff55b767e/bat_eval/cpu_detection.py#L14-L21
to simply:
`import nms_slow as nms`

If you do that you don't need to run `python setup.py build_ext --inplace`.

**Comment by TheFunEmbargo** [comment]
It works!! Thanks for bearing with me!!

**Comment by macaodha** [comment]
Glad to hear! I'll close this issue.
