### ISSUE TITLE
Practical use of BatDetective algorithm

### ISSUE THREAD

**Issue by steverlucas** [macaodha/batdetect#2]
A member of a local bat group (in Wales) has downloaded the code and has managed to get it to run on the test files. I subsequently sent him a large number of WAV files organised in daily folders to look at - he has some questions:

1. does the code only look at a single folder? Will it look at nested folders?

2. When the code runs, it generates a CSV file for each individual WAV files. This means he gets as many CSV files as there are WAV files. For a few files this is not a big problem but for hundreds if not thousands of files then that results in a lot of work to knit everything together.

Thanks
Steve Lucas

**Comment by macaodha** [comment]
Hi Steve,

I've updated the code to address both of your issues:

1) It will now look at all sub directories for the path specified [here](https://github.com/macaodha/batdetect/blob/05d85c9893dd1276f25f2717dab3c446686093f0/bat_eval/run_detector.py#L95). 

2) There is a flag called `save_individual_results` that can be set to `False` [here](https://github.com/macaodha/batdetect/blob/05d85c9893dd1276f25f2717dab3c446686093f0/bat_eval/run_detector.py#L90) to disable outputting results for individual files. 

Best of luck!
