### ISSUE TITLE
Looping through large amounts of data

### ISSUE THREAD

**Issue by glynnwh** [macaodha/batdetect#3]
Hi Oisin,

I'm working with Kate Jones using BatDetect to analyse sound files from Jersey. I've got data from 90 sites across the island, each site surveyed 3 times and stored in different folders.

The file structure is as follows:

Survey night (with reference and date)\grid square\.wav files (around 2000-2500 per night)

There were 15 survey nights and most have 30 grid squares for each, although some have fewer where repeats were carried out.

The issue we are having is that we would like to run a loop in BatDetect so that it automatically cycles through each folder and outputs the results in the same folder as the data. But we are unsure whether to alter the code at lines 94-95 and put the loop there, or whether to write a separate piece of code which feeds in at this point.

We'd be very grateful for any suggestions you have on the best way of doing this.

Many thanks and best wishes,

Henry Glynn

**Comment by macaodha** [comment]
Hi Henry, 

I think you have three options:

1) Don't do anything. The code will output the results in a single csv file and you can split that up any way you want afterwards. My vote. 

2) Have you tried running the code as is. It should output the results in a separate folder for each survey night - but it won't be in the same folder as the data. 

3) Alternatively, if I understand your request correctly,  you could do the following:
```
data_dir = 'wavs/'
op_ann_dir =op_ann_dir
op_ann_dir_ind = op_ann_dir
```
  And on [line 42](https://github.com/macaodha/batdetect/blob/master/bat_eval/run_detector.py#L142) set:
```
op_file_name = op_ann_dir_ind + file_name_basename[:-4] + '-sceneRect.csv'
```

Best of luck!

**Comment by macaodha** [comment]
It should have no problem with either of the following settings:

```
wav_dir/file_1.wav
wav_dir/file_2.wav
wav_dir/file_3.wav
...
```

or 

```
wav_dir/wav_sub_dir_1/file_1.wav
wav_dir/wav_sub_dir_1/file_2.wav
wav_dir/wav_sub_dir_2/file_3.wav
...
```

It looks like you might be having problems with combining back-slashes and forward-slashes - `individual_results/\C_1`. I think this is because windows uses back-slashes by [default](https://medium.com/@ageitgey/python-3-quick-tip-the-easy-way-to-deal-with-file-paths-on-windows-mac-and-linux-11a072b58d5f). 

I updated the code, so if you re-download `run_detector.py` it should hopefully not throw an error. Unfortunately, I dont have a windows machine handy so I cant test it myself right now.

**Comment by glynnwh** [comment]
Hi Oisin,

Thank you so much for this. I’ve just re-run your updated code and it has worked for my test data. When my main dataset is ready tomorrow, I’ll try it with that.

Many thanks and best wishes,

Henry

**Comment by macaodha** [comment]
Great.
