### ISSUE TITLE
Provide metadata for headers in *-sceneRect.csv

### ISSUE THREAD

**Issue by lionel68** [macaodha/batdetect#4]
Thanks a lot for putting together and making this great tool available!

Could you add somewhere in the readme file of bat_eval/ the information stored in the different columns, some are pretty straightforward to understand (ie DetectorConfidence) but others are rather cryptic (ie Spec_x1).

**Comment by macaodha** [comment]
Hi @lionel68,

Thanks for your comments. Agreed, the info in the -sceneRect.csv files is a bit cryptic, they used for loading the annotations in [AudioTagger](https://github.com/groakat/AudioTagger) and do not provide any extra info beyond what is available in the main results.csv file i.e. the call end times is just a fixed window size, not predicted.

**Comment by macaodha** [comment]
Also, if you have any other suggestions on how I can improve the tool I would be happy to hear them. Thanks

**Comment by lionel68** [comment]
So, do we have some infos on the headers now?

**Comment by macaodha** [comment]
You will find an updated description in the readme:


* The code outputs annotations as one big csv file. The location where to save the file is specified with the variable:
  `op_file_name_total = 'res/op_file.csv'`  
  It contains three fields `file_name`, `detection_time`, and `detection_prob` which indicated the time in file and detector confidence (higher is more confident) for each detected call.
* It also saves the outputs in a format compatible with [AudioTagger](https://github.com/groakat/AudioTagger). The output directory for these annotations is specified as:
`op_ann_dir = 'res/'`  
The individual `*-sceneRect.csv` files contain the same information that is specified in the main results file `op_file_name_total`, where `LabelStartTime_Seconds` corresponds to `detection_time` and `DetectorConfidence` corresponds to `detection_prob`. The additional fields (e.g. `Spec_x1`) are specific to Audiotagger and do not contain any extra information.
