### ISSUE TITLE
File directory issues

### ISSUE THREAD

**Issue by glynnwh** [macaodha/batdetect#5]
Dear Oisin,

Thank you for your help with my previous issue. 

I am now trying to run the code on data stored on a server and have set 'data_dir' to the appropriate pathway. However now when I run the code it seems to stall at the point where the audio files are read.

Is there any reason this may be the case? For example does the data need to be stored locally?

Many thanks and best wishes,

Henry

**Comment by macaodha** [comment]
You could put a print statement in [here](https://github.com/macaodha/batdetect/blob/9710bfd1cfe8d075f3f0b8013402335b1d6247c4/bat_eval/run_detector.py#L104) to see if it's pointing to your files e.g. `print(audio_files)`
