### ISSUE TITLE
WAV Audiomoth file extension not read by Bat Detective

### ISSUE THREAD

**Issue by steverlucas** [macaodha/batdetect#6]
Hi Oisin, I have just noticed that Bat Detective code is not reading files generated with the Audiomoth ie .WAV it will though read file names ending .wav Apparently Audiomoth defaults to .WAV although I am told that this will be changed at some point. is there a simple work around please?
Steve

**Comment by macaodha** [comment]
Hi @steverlucas, 

I've updated the code to read both .wav and .WAV files.
