### ISSUE TITLE
package version and compatibility issues

### ISSUE THREAD

**Issue by mikeyEcology** [macaodha/batdetect#8]
Hi, 
I've tried unsuccessfully to train models with the code from `bat_train` using many different approaches and I'm wondering if it is possible to share an environment (e.g., [a conda environment](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#viewing-a-list-of-your-environments)) in which the code can be run successfully.

One approach I've tried is installing all of the same versions of the software presented under Requirements [on this page](https://github.com/macaodha/batdetect/tree/master/bat_train). I'm unable to obtain some of these versions (e.g., `pip install libgcc==7.2.0` doesn't work). I tried installing those packages with versions as recommended that I can and then the recent version for others, but this leads to errors when trying `run_comparison.py`. I also tried installing the most recent version of all of these packages on python2.7, which also leads to errors. I've also tried updating the code to python3, and running there, but I'm having similar issues. I have tried this on both an HPC with GPUs and a laptop.

It would be great if you could make available an environment with the packages installed in a manner that they will run with the code. This is a great way to make the code accessible to more scientists.
Thank you

**Comment by macaodha** [comment]
Hi @mikeyEcology 

I just tested it again now and you can find a list of packages and versions below that worked for me again. Regarding the `libgcc` issue, I think it is used with `weave` for the random forest. You can disable that as it is not required for the main CNN code. Also if you are having any issues with `cythnon` used for the non-max suppression code in `nms.pyx`, there is a drop in replacement in `nms_slow.py` that can be imported instead if you can't get the other one working. 

I'm actually working on an improved version of this code base that is using Python 3 and PyTorch, so hopefully that will be much easier to get up and running. This code was based on `Lasagne` which I don't believe is support much anymore. 

Not sure if that fully addresses your issue, but hopefully there is enough info to get it up and running.  

```
Python 2.7.16 :: Anaconda custom (64-bit)
pandas==0.19.2
Lasagne==0.2.dev1
scikit_image==0.13.0
matplotlib==2.2.3
numpy==1.11.3
seaborn==0.8
weave==0.16.0
Theano==0.9.0.dev4
scipy==1.0.1
Cython==0.29.16
joblib==0.14.1
scikit_learn==0.22.2.post1
skimage==0.0
```

**Comment by mikeyEcology** [comment]
Thank you @macaodha !
